// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using server.Models;

namespace server.Migrations
{
    [DbContext(typeof(KafeterijaContext))]
    [Migration("20210327143313_V4")]
    partial class V4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PiceSto", b =>
                {
                    b.Property<int>("PicaID")
                        .HasColumnType("int");

                    b.Property<int>("StoloviID")
                        .HasColumnType("int");

                    b.HasKey("PicaID", "StoloviID");

                    b.HasIndex("StoloviID");

                    b.ToTable("PiceSto");
                });

            modelBuilder.Entity("server.Models.Kafeterija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrojStolova")
                        .HasColumnType("int")
                        .HasColumnName("BrojStolova");

                    b.Property<int?>("MeniID")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Naziv");

                    b.HasKey("ID");

                    b.HasIndex("MeniID");

                    b.ToTable("Kafeterija");
                });

            modelBuilder.Entity("server.Models.Meni", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("ID");

                    b.ToTable("Meni");
                });

            modelBuilder.Entity("server.Models.Pice", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cena")
                        .HasColumnType("int")
                        .HasColumnName("Cena");

                    b.Property<int?>("MeniID")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Naziv");

                    b.HasKey("ID");

                    b.HasIndex("MeniID");

                    b.ToTable("Pice");
                });

            modelBuilder.Entity("server.Models.Sto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("KafeterijaID")
                        .HasColumnType("int");

                    b.Property<int?>("MeniID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("KafeterijaID");

                    b.HasIndex("MeniID");

                    b.ToTable("Sto");
                });

            modelBuilder.Entity("PiceSto", b =>
                {
                    b.HasOne("server.Models.Pice", null)
                        .WithMany()
                        .HasForeignKey("PicaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Models.Sto", null)
                        .WithMany()
                        .HasForeignKey("StoloviID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("server.Models.Kafeterija", b =>
                {
                    b.HasOne("server.Models.Meni", "Meni")
                        .WithMany()
                        .HasForeignKey("MeniID");

                    b.Navigation("Meni");
                });

            modelBuilder.Entity("server.Models.Pice", b =>
                {
                    b.HasOne("server.Models.Meni", null)
                        .WithMany("Stavke")
                        .HasForeignKey("MeniID");
                });

            modelBuilder.Entity("server.Models.Sto", b =>
                {
                    b.HasOne("server.Models.Kafeterija", null)
                        .WithMany("Stolovi")
                        .HasForeignKey("KafeterijaID");

                    b.HasOne("server.Models.Meni", "Meni")
                        .WithMany()
                        .HasForeignKey("MeniID");

                    b.Navigation("Meni");
                });

            modelBuilder.Entity("server.Models.Kafeterija", b =>
                {
                    b.Navigation("Stolovi");
                });

            modelBuilder.Entity("server.Models.Meni", b =>
                {
                    b.Navigation("Stavke");
                });
#pragma warning restore 612, 618
        }
    }
}
