// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using server.Models;

namespace server.Migrations
{
    [DbContext(typeof(KafeterijaContext))]
    partial class KafeterijaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("server.Models.Kafeterija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MeniID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MeniID");

                    b.ToTable("Kafeterija");
                });

            modelBuilder.Entity("server.Models.Meni", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("ID");

                    b.ToTable("Meni");
                });

            modelBuilder.Entity("server.Models.Narudzbina", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("ID");

                    b.ToTable("Narudzbina");
                });

            modelBuilder.Entity("server.Models.Pice", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cena")
                        .HasColumnType("int")
                        .HasColumnName("Cena");

                    b.Property<int?>("MeniID")
                        .HasColumnType("int");

                    b.Property<int?>("NarudzbinaID")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Naziv");

                    b.HasKey("ID");

                    b.HasIndex("MeniID");

                    b.HasIndex("NarudzbinaID");

                    b.ToTable("Pice");
                });

            modelBuilder.Entity("server.Models.Sto", b =>
                {
                    b.Property<int>("Broj")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("KafeterijaID")
                        .HasColumnType("int");

                    b.Property<int?>("MeniID")
                        .HasColumnType("int");

                    b.Property<int?>("NarudzbinaID")
                        .HasColumnType("int");

                    b.HasKey("Broj");

                    b.HasIndex("KafeterijaID");

                    b.HasIndex("MeniID");

                    b.HasIndex("NarudzbinaID");

                    b.ToTable("Sto");
                });

            modelBuilder.Entity("server.Models.Kafeterija", b =>
                {
                    b.HasOne("server.Models.Meni", "Meni")
                        .WithMany()
                        .HasForeignKey("MeniID");

                    b.Navigation("Meni");
                });

            modelBuilder.Entity("server.Models.Pice", b =>
                {
                    b.HasOne("server.Models.Meni", null)
                        .WithMany("Stavke")
                        .HasForeignKey("MeniID");

                    b.HasOne("server.Models.Narudzbina", null)
                        .WithMany("Pica")
                        .HasForeignKey("NarudzbinaID");
                });

            modelBuilder.Entity("server.Models.Sto", b =>
                {
                    b.HasOne("server.Models.Kafeterija", null)
                        .WithMany("Stolovi")
                        .HasForeignKey("KafeterijaID");

                    b.HasOne("server.Models.Meni", "Meni")
                        .WithMany()
                        .HasForeignKey("MeniID");

                    b.HasOne("server.Models.Narudzbina", "Narudzbina")
                        .WithMany()
                        .HasForeignKey("NarudzbinaID");

                    b.Navigation("Meni");

                    b.Navigation("Narudzbina");
                });

            modelBuilder.Entity("server.Models.Kafeterija", b =>
                {
                    b.Navigation("Stolovi");
                });

            modelBuilder.Entity("server.Models.Meni", b =>
                {
                    b.Navigation("Stavke");
                });

            modelBuilder.Entity("server.Models.Narudzbina", b =>
                {
                    b.Navigation("Pica");
                });
#pragma warning restore 612, 618
        }
    }
}
